#define MAXNOME 50 //ESPAÇO MAXIMO QUE UMA PALAVRA PODE OCUPAR EM QUALQUER OCASIÃO.
#define MAXTEXT 3000
#define TAMFILA 1700

#ifndef INC_3PPP_STRUCTS_H
#define INC_3PPP_STRUCTS_H


#endif //INC_3PPP_STRUCTS_H
